spring:
  application:
    name: petlog
  datasource:
    url: "${DB_URL}"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

server:
  port: 8080

token:
  secret: "${TOKEN_SECRET}"
  expiration-time: "${TOKEN_EXPIRATION_TIME}"

springdoc:
  api-docs:
    path: /swagger-ui/users/v3/api-docs
  swagger-ui:
    path: /swagger-ui/users/index.html

openapi:
  service:
    # API Gateway 포트
    url: "${API_GATEWAY}"