spring:
  ai:
    openai:
      api-key: "${API_KEY}"

  datasource:
    url: "${DB_URL}"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

token:
  secret: "${TOKEN_SECRET}"
  expiration-time: "${TOKEN_EXPIRATION_TIME}"

cloud:
  aws:
    s3:
      access-key: "${AWS_ACCESS_KEY}"
      secret-key: "${AWS_SECRET_KEY}"
      bucket-name: "${AWS_S3_BUCKET}"
    region: "${AWS_BUCKET_REGION}"

springdoc:
  api-docs:
    path: "${SWAGGER_DOCS}"
  swagger-ui:
    path: "${SWAGGER_UI}"
